services:
  front:
    container_name: front
    build:
      context: .docker/develop/node
    volumes:
      - ./:/app
    tty: true
    hostname: front
    networks:
      - front
      - gateway

networks:
  front:
    name: front

  gateway:
    name: gateway
    external: true
