services:
  front_dev:
    container_name: front_dev
    build:
      context: .docker/develop/node
    volumes:
      - ./:/app
    tty: true
    hostname: front_dev
    command: npm run dev
    networks:
      - front_dev
      - gateway

networks:
  front_dev:
    name: front_dev

  gateway:
    name: gateway
    external: true
